name: deploy

on:
  push:
    branches:
      - master
      - review

env:
  BURGER_API_URL: https://norma.nomoreparties.space/api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: build project
        run: npm run build
        env:
          BURGER_API_URL: ${{ vars.BURGER_API_URL || env.BURGER_API_URL }}

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
